### PR TITLE
Add sarama wrappers

### PR DESCRIPTION
**Pull request by rabisg**
Refactors integrations/kafka to enable more kafka+golang libraries

### CODE REVIEW

**Comment by rabisg** [comment]
Please let me know if the approach looks good and I can add more tests/docs etc

**Review by piochelepiotr — COMMENTED** [review]
👋 Hi @rabisg , sorry we missed this PR, thanks for making it.
We will review it in the next few days.

**Review by piochelepiotr — APPROVED** [review]
Looks good :)
Tested internally and everything worked well.
Thanks for the contribution!

**Comment by rabisg** [comment]
I dont have permissions to merge this. Can you please merge this?

**Pull request merged**
